apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 80               # We listen on standard HTTP port 80 externally
    targetPort: 80         # Points to port 80 inside your container
  selector:
    app: result

